import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  Image,
  TouchableOpacity,
  Pressable,
  StyleSheet,
  DimensionValue,
  useWindowDimensions,
} from 'react-native';
import { motion, AnimatePresence } from 'motion/react';
import { FloatingLogoCard } from './FloatingLogoCard';
import { CreateAccountPage } from './CreateAccountPage';
import { VerifyOtpPage } from './VerifyOtpPage';
import { MainDashboardPage } from './MainDashboardPage';
import { TellUsAboutCouplePage } from './TellUsAboutCouplePage';
import { ColorTheme, ViewMode } from '../types';
import { THEMES } from '../constants/themes';

interface MobileLandingPageProps {
  viewMode: ViewMode;
  currentTheme: ColorTheme;
  onOpenGetStarted: () => void;
  onOpenLogin: () => void;
  loginSuccessTrigger?: number;
}

export const MobileLandingPage: React.FC<MobileLandingPageProps> = ({
  viewMode,
  currentTheme,
  onOpenGetStarted,
  onOpenLogin,
  loginSuccessTrigger,
}) => {
  const { width } = useWindowDimensions();
  const isMobile = width < 768;
  const theme = THEMES[currentTheme];
  const [activeScreen, setActiveScreen] = useState<'landing' | 'create-account' | 'verify-otp' | 'dashboard' | 'tell-us-about-couple'>('landing');
  const [initialDashboardTab, setInitialDashboardTab] = useState<'home' | 'my-wedding'>('home');
  const [userName, setUserName] = useState<string>('');
  const [userMobile, setUserMobile] = useState<string>('');
  const [userEmail, setUserEmail] = useState<string>('');
  const [userId, setUserId] = useState<string>('');
  const [weddingProfile, setWeddingProfile] = useState<{
    marriageType?: string;
    brideName?: string;
    groomName?: string;
    weddingDate?: string;
    location?: string;
    guestCount?: string;
    budget?: string;
    weddingStyle?: string;
  } | null>(null);

  useEffect(() => {
    if (loginSuccessTrigger && loginSuccessTrigger > 0) {
      const currentId = userId || 'TOT-' + Math.floor(100000 + Math.random() * 900000);
      setUserId(currentId);
      saveUserDataToStorage(userName, userMobile, userEmail, currentId, weddingProfile);
      setActiveScreen('dashboard');
    }
  }, [loginSuccessTrigger]);

  // Restore saved registration / couple details from localStorage on initial load
  useEffect(() => {
    try {
      const saved = localStorage.getItem('wedding_app_user_data');
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed.userName) setUserName(parsed.userName);
        if (parsed.userMobile) setUserMobile(parsed.userMobile);
        if (parsed.userEmail) setUserEmail(parsed.userEmail);
        if (parsed.userId) setUserId(parsed.userId);
        if (parsed.weddingProfile) setWeddingProfile(parsed.weddingProfile);
      }
    } catch (e) {
      console.error('Error restoring saved user data:', e);
    }
  }, []);

  // Save profile state whenever changes occur
  const saveUserDataToStorage = (
    nameVal: string,
    mobileVal: string,
    emailVal: string,
    idVal: string,
    profileVal: typeof weddingProfile
  ) => {
    try {
      localStorage.setItem(
        'wedding_app_user_data',
        JSON.stringify({
          userName: nameVal,
          userMobile: mobileVal,
          userEmail: emailVal,
          userId: idVal,
          weddingProfile: profileVal,
        })
      );
    } catch (e) {
      console.error('Error saving user data:', e);
    }
  };

  // Image generated by generate_image tool with upper background space
  const coupleImage = '/src/assets/images/couple_with_top_space_1786458075338.jpg';

  const handleGetStartedPress = () => {
    setActiveScreen('create-account');
  };

  const handleCreateAccountSubmit = (data: { name: string; mobile: string; email: string }) => {
    const newName = data.name || '';
    const newMobile = data.mobile || '';
    const newEmail = data.email || '';
    const generatedId = 'TOT-' + Math.floor(100000 + Math.random() * 900000);
    setUserName(newName);
    setUserMobile(newMobile);
    setUserEmail(newEmail);
    setUserId(generatedId);
    saveUserDataToStorage(newName, newMobile, newEmail, generatedId, weddingProfile);
    setActiveScreen('verify-otp');
  };

  const handleVerifySuccess = () => {
    const currentId = userId || 'TOT-' + Math.floor(100000 + Math.random() * 900000);
    setUserId(currentId);
    saveUserDataToStorage(userName, userMobile, userEmail, currentId, weddingProfile);
    setActiveScreen('dashboard');
  };

  const handleCoupleContinue = (data: any) => {
    setWeddingProfile(data);
    let updatedName = userName;
    if (data.brideName && data.groomName) {
      updatedName = `${data.brideName} & ${data.groomName}`;
      setUserName(updatedName);
    }
    saveUserDataToStorage(updatedName, userMobile, userEmail, userId, data);
    setInitialDashboardTab('my-wedding');
    setActiveScreen('dashboard');
  };

  const handleLogout = () => {
    setUserName('');
    setUserMobile('');
    setUserEmail('');
    setUserId('');
    setWeddingProfile(null);
    try {
      localStorage.removeItem('wedding_app_data');
      localStorage.removeItem('wedding_app_user_data');
    } catch (e) {
      console.error(e);
    }
    setActiveScreen('landing');
  };

  const innerLandingContent = (
    <View style={[styles.innerContainer, { backgroundColor: '#FAF6EE' }]}>
      {/* ================= TOP PHOTO SECTION (56% Height) ================= */}
      <View style={styles.topPhotoSection}>
        {/* Background Image with subtle entrance animation */}
        <motion.div
          initial={{ scale: 1.02, opacity: 0.9 }}
          animate={{ scale: 1, opacity: 1 }}
          transition={{ duration: 0.8, ease: 'easeOut' }}
          className="absolute inset-0 z-0"
        >
          <Image
            source={{ uri: coupleImage }}
            style={styles.backgroundImage}
            resizeMode="cover"
          />
          {/* Subtle gradient overlay tint */}
          <div className="absolute inset-0 bg-gradient-to-b from-black/10 via-transparent to-transparent" />
        </motion.div>

        {/* Floating White Square Logo Card + Title overlay */}
        <View style={styles.logoCardWrapper}>
          <FloatingLogoCard
            primaryColor="#581420"
            brandName="Tale of Two"
            tagline="Your Dream, Our Passion"
          />
        </View>

        {/* Soft Gradient Mask at Bottom blending seamlessly into lower container */}
        <div
          className="absolute bottom-0 left-0 right-0 h-28 sm:h-36 z-10 pointer-events-none"
          style={{
            background: `linear-gradient(to bottom, rgba(250, 246, 238, 0) 0%, rgba(250, 246, 238, 0.85) 75%, #FAF6EE 100%)`,
          }}
        />
      </View>

      {/* ================= BOTTOM TEXT & ACTION SECTION (44% Height) ================= */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.15 }}
        className="relative z-20 h-[44%] min-h-[44%] w-full flex flex-col justify-between px-7 pb-6 pt-1"
        style={{ backgroundColor: '#FAF6EE' }}
      >
        <View style={styles.textContent}>
          {/* Stacked Heading in 3 punchy lines matching exact image colors */}
          <Text style={styles.headingText}>
            <Text style={{ color: '#581420' }}>Your Wedding.{'\n'}</Text>
            <Text style={{ color: '#2A2425' }}>Your Story.{'\n'}</Text>
            <Text style={{ color: '#2A2425' }}>Beautifully Planned.</Text>
          </Text>

          {/* Small, clean body text */}
          <Text style={styles.bodyText}>
            Plan your dream wedding with{'\n'}AI-powered planning and{'\n'}trusted vendors.
          </Text>
        </View>

        {/* Actions Section */}
        <View style={styles.actionsWrapper}>
          {/* Primary CTA: Rounded burgundy button directing to page 2 */}
          <TouchableOpacity
            activeOpacity={0.88}
            onPress={handleGetStartedPress}
            style={styles.primaryButton}
          >
            <Text style={styles.primaryButtonText}>Get Started</Text>
          </TouchableOpacity>

          {/* Secondary CTA: Centered at very bottom */}
          <View style={styles.secondaryContainer}>
            <Text style={styles.secondaryText}>
              Already have an account?{' '}
            </Text>
            <Pressable onPress={onOpenLogin}>
              <Text style={styles.loginLink}>Login</Text>
            </Pressable>
          </View>
        </View>
      </motion.div>
    </View>
  );

  return (
    <View style={[styles.exactCardContainer, isMobile ? styles.exactCardContainerMobile : styles.exactCardContainerDesktop]}>
      <AnimatePresence mode="wait">
        {activeScreen === 'landing' && (
          <motion.div
            key="landing"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
            className="w-full h-full"
          >
            {innerLandingContent}
          </motion.div>
        )}
        {activeScreen === 'create-account' && (
          <motion.div
            key="create-account"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
            className="w-full h-full"
          >
            <CreateAccountPage
              onBack={() => setActiveScreen('landing')}
              onSuccessSubmit={handleCreateAccountSubmit}
            />
          </motion.div>
        )}
        {activeScreen === 'verify-otp' && (
          <motion.div
            key="verify-otp"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
            className="w-full h-full"
          >
            <VerifyOtpPage
              mobileNumber={userMobile}
              onBack={() => setActiveScreen('create-account')}
              onChangeMobile={() => setActiveScreen('create-account')}
              onVerifySuccess={handleVerifySuccess}
            />
          </motion.div>
        )}
        {activeScreen === 'dashboard' && (
          <motion.div
            key="dashboard"
            initial={{ opacity: 0, scale: 0.98 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.98 }}
            transition={{ duration: 0.35 }}
            className="w-full h-full"
          >
            <MainDashboardPage
              userName={userName}
              userMobile={userMobile}
              userEmail={userEmail}
              userId={userId}
              weddingProfile={weddingProfile}
              initialTab={initialDashboardTab}
              onLogout={handleLogout}
              onNavigateToCoupleOnboarding={() => setActiveScreen('tell-us-about-couple')}
            />
          </motion.div>
        )}
        {activeScreen === 'tell-us-about-couple' && (
          <motion.div
            key="tell-us-about-couple"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            transition={{ duration: 0.3 }}
            className="w-full h-full"
          >
            <TellUsAboutCouplePage
              initialBrideName={userName}
              onBack={() => setActiveScreen('dashboard')}
              onContinue={handleCoupleContinue}
            />
          </motion.div>
        )}
      </AnimatePresence>
    </View>
  );
};

const styles = StyleSheet.create({
  innerContainer: {
    width: '100%',
    height: '100%',
    flexDirection: 'column',
    justifyContent: 'space-between',
    overflow: 'hidden',
  },
  topPhotoSection: {
    position: 'relative',
    height: '56%' as DimensionValue,
    width: '100%',
    overflow: 'hidden',
    justifyContent: 'space-between',
    paddingTop: 20,
    paddingHorizontal: 16,
  },
  backgroundImage: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  logoCardWrapper: {
    position: 'relative',
    zIndex: 10,
    width: '100%',
    alignItems: 'center',
    paddingTop: 8,
  },
  textContent: {
    marginVertical: 'auto',
    gap: 12,
  },
  headingText: {
    fontFamily: "'Cormorant Garamond', Georgia, serif",
    fontSize: 32,
    fontWeight: '700',
    lineHeight: 36,
    letterSpacing: -0.2,
    textAlign: 'left',
  },
  bodyText: {
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    fontSize: 12.5,
    fontWeight: '400',
    lineHeight: 18,
    textAlign: 'left',
    color: '#635B5C',
  },
  actionsWrapper: {
    width: '100%',
    gap: 12,
    paddingTop: 4,
  },
  primaryButton: {
    width: '100%',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    backgroundColor: '#581420',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#581420',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
  },
  primaryButtonText: {
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  secondaryContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  secondaryText: {
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    fontSize: 11.5,
    color: '#635B5C',
  },
  loginLink: {
    fontFamily: "'Plus Jakarta Sans', system-ui, sans-serif",
    fontSize: 11.5,
    fontWeight: '700',
    color: '#581420',
  },
  exactCardContainer: {
    width: '100%',
    backgroundColor: '#FAF6EE',
  },
  exactCardContainerDesktop: {
    maxWidth: 330,
    height: 680,
    maxHeight: '92vh' as any,
    borderRadius: 28,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#e2ddd5',
    marginHorizontal: 'auto',
    boxShadow: '0 25px 60px -15px rgba(0, 0, 0, 0.65)',
  },
  exactCardContainerMobile: {
    height: '100%',
    flex: 1,
  },
});
